name: Upload to COS

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install coscmd
      run: sudo pip install coscmd
    - name: Configure coscmd
      env:
        SECRET_ID: ${{ secrets.SECRETID }}
        SECRET_KEY: ${{ secrets.SECRETKEY }}
        BUCKET: pangtouyu-1320549472
        REGION: ap-nanjing
      run: coscmd config -a $SECRET_ID -s $SECRET_KEY -b $BUCKET -r $REGION
    - name: Upload
      run: coscmd upload -rfs --delete ./ / --ignore "./.git/*"
